#pragma once
#include <stdio.h>
#include <Windows.h>

#define IOCTL_IMGBASE CTL_CODE(FILE_DEVICE_UNKNOWN,0x888,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define IOCTL_IMGBASEOUT CTL_CODE(FILE_DEVICE_UNKNOWN,0x889,METHOD_OUT_DIRECT,FILE_ANY_ACCESS)
#define IOCTL_READMEM CTL_CODE(FILE_DEVICE_UNKNOWN,0x999,METHOD_BUFFERED,FILE_ANY_ACCESS)

#pragma warning(disable: 4996)
HANDLE hHandle;
WCHAR path[] = L"\\\\.\\ReadMem";
VOID sendBuffer(PVOID buf);
